name: Build & Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.REG_TOKEN }}" \
          | docker login docker.io \
              --username "${{ secrets.REG_USER }}" \
              --password-stdin

    - name: Build and tag image
      run: |
        docker build \
          -t docker.io/${{ secrets.REG_USER }}/ml-btp:latest .

    - name: Push image
      run: |
        docker push \
          docker.io/${{ secrets.REG_USER }}/ml-btp:latest
